### ISSUE TITLE
Removing dependency should disable dependent plugins

### ISSUE THREAD

**Issue by RobLui** [Flamenco/grav-admin-media-actions#1]
Hi,

The plugin breaks the complete admin if turned off when dependent children are not turned off yet :) 

![error image](https://i.imgur.com/pPuGYBy.png)

**Comment by Flamenco** [comment]
Thanks.  I would have expected the Grav runtime would disable the dependents as well, but it looks like it only manages dependents on installing.  I will post a hotfix to workaround.

**Comment by Flamenco** [comment]
<img width="1063" alt="screen shot 2018-02-24 at 1 57 15 am" src="https://user-images.githubusercontent.com/819940/36626746-13f2696e-1906-11e8-8ac9-fd1010724e7b.png">

**Comment by Flamenco** [comment]
This is actually a problem with the plugins that require this one, so I am closing and will update the dependents.

**Comment by Flamenco** [comment]
@RobLui The new versions made it to the Grav repo.  Please confirm that fixed your issue.  Thanks!

**Comment by RobLui** [comment]
Thanks, I will check when I get home :)

**Comment by RobLui** [comment]
Issue resolved, but now the message doesn't dissapear untill I set media actions to true. I think this should be a little less prominent, and would only be needed untill a page refresh or page switch happens. If that's done, this is an awesome fix! :)

**Comment by Flamenco** [comment]
You need to disable the plugins with the warnings (MediaMove or MediaReplace) and the message will disappear, or enable/install the dependencies (MediaActions).  I think it is dangerous to have a plugin enabled that is not functioning, but the Grav API does not have a simple way to disable on load.  By the time I write message, the plugin is already loaded without the dependency.  

At least you don't need to SSH to the server to fix it :)

Grav really needs some internal functionality to make that happen automatically...  As a plugin designer, I should not need to write workarounds when I have declared internal dependencies to the system.

BTW which plugin are you using?

**Comment by RobLui** [comment]
Yeah I know, and I've seen your PR to the Grav core, which I support. And indeed, I'm pretty confident using ssh / terminal commands, but if a normal user had this issue, they'd be screwed as they would not see the possibility of how to fix it. ^^ 

I'm currently testing all plugins available for Grav, and this happened in this plugin where I created the issue :) - admin-media-actions

**Comment by Flamenco** [comment]
admin-media-actions does nothing by itself.  Do you have admin-media-move or admin-media-replace also installed?

**Comment by RobLui** [comment]
Oh, yes indeed :) I have both, and the error occured in the admin-media-move plugin, not in the admin-replace-plugin if I remember correctly before the update

**Comment by Flamenco** [comment]
They both will now show the error if you pull out the admin-media-actions dependency.  I am going to suggest the core catch all plugin exceptions and disable them with option to email developer instead of showing that frightening screen to end users.  

Thanks for your input!

**Comment by RobLui** [comment]
Thanks for the fix! :)
